# ebean configuration
ebean:
  dumpMetricsOnShutdown: true
  dumpMetricsOptions: loc,sql,hash
  ddl:
    generate: true
    run: true
  debug:
    sql: true
    lazyload: true
  logging: all

# database configuration
datasource:
  db:
    username: root
    password: Kappa123
    platform: mariadb # Cambiado de sqlite a mariadb
    ddlMode: dropCreate # none | dropCreate | migrations
    dbName: conserjeria
    url: jdbc:mariadb://localhost:3306/conserjeria  # Cambiado el URL para apuntar a MariaDB
